sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
# install the gwt-material library before we build the demo
- git clone -b release_2.2 https://github.com/GwtMaterialDesign/gwt-material.git
- cd gwt-material
- mvn install -DskipTests=true -DdryRun=true
- cd ..
# install the gwt-material-themes library
- git clone -b release_2.2 https://github.com/GwtMaterialDesign/gwt-material-themes.git
- cd gwt-material-themes
- mvn install -DskipTests=true -DdryRun=true
- cd ..
# install the gwt-material-addins library
- git clone -b release_2.2 https://github.com/GwtMaterialDesign/gwt-material-addins.git
- cd gwt-material-addins
- mvn install -DskipTests=true -DdryRun=true
- cd ..
# install the gwt-material-addins library
- git clone -b master https://github.com/GwtMaterialDesign/gwt-material-amcharts4.git
- cd gwt-material-amcharts4
- mvn install -DskipTests=true -DdryRun=true
- cd ..
install: true
script:
- mvn clean install -DdryRun=true -Dlicense.failOnMissingHeader=true -Dlicense.failOnNotUptodateHeader=true
after_success:
- chmod +x .utility/*
- .utility/update_demo_site.sh